config/routes.rb
SampleApp::Application.routes.draw do
  root 'static_pages#home'
  match "/help",     to: 'static_pages#help',     via: 'get'
  match "/about",    to: 'static_pages#about',    via: 'get'
  match "/contacts", to: 'static_pages#contacts', via: 'get'
  match "/signup",   to: 'users#new',             via: 'get'
  match '/signin',   to: 'sessions#new',          via: 'get'
  match '/signout',  to: 'sessions#destroy',      via: 'delete'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :books

  resources :authors

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contacts
  end

  def not_found
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_non_signed_in.html.erb
<% provide(:title, 'Home page') %>
<div class="center hero-unit">
  <h1>Welcome to the Sample App!</h1>
  
    <h2>
      This is the home page for the
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
    </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/static_pages/_signed_in.html.erb
<% provide(:title, 'Home page') %>
<div class="center hero-unit">
  <h1>Welcome to the Sample App!</h1>
  
  <%= link_to "Books", books_path, class: "btn btn-large" %>
  <%= link_to "Authors", authors_path, class: "btn btn-large" %>

</div>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>

<%= link_to() %>"

app/views/static_pages/contacts.html.erb
<% provide(:title, 'Contacts') %>
<h1>Contacts page</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
  <% if signed_in? %>
    <%= render 'signed_in' %>  
  <% else %>
    <%= render 'non_signed_in' %>
  <% end %>