config/routes.rb
SampleApp::Application.routes.draw do
  root 'static_pages#home'
  match "/help",     to: 'static_pages#help',     via: 'get'
  match "/about",    to: 'static_pages#about',    via: 'get'
  match "/contacts", to: 'static_pages#contacts', via: 'get'
  match "/signup",   to: 'users#new',             via: 'get'
  match '/signin',   to: 'sessions#new',          via: 'get'
  match '/signout',  to: 'sessions#destroy',      via: 'delete'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :books

  resources :authors

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :relationships
  has_many :books, through: :relationships
  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :current_author, only: [:show, :add_book]
  before_action :filter_non_signed, only: [:index, :new, :show]

  def index
    if params[:search]
      @authors = Author.find_by(name: params[:search])
    else
      @authors = Author.paginate(page: params[:page])
    end
  end

  def show
  end

  def add_book(book)
    @author.relationships.create(book: book)
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(params.require(:author).permit(:name))

    if @author.save
      flash.now[:success] = "Author successfully created!"
    else
      flash.now[:error] = "Author creation failed!"
    end

    render 'new'
  end

  private

    def current_author
      @author = Author.find(params[:id])
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_author.html.erb
<li>
  <%= link_to author.name, author %>
  <ul class="custom-sub-list">
    <% author.books.map do |book| %>
      <li>
        <%= book.name %>
      </li>
    <% end %>
  </ul>
  <% if current_user.admin? %>
    | <%= link_to "delete", author, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/authors/index.html.erb
<% provide(:title, 'All books') %>
<h1>All authors</h1>

<%= form_tag(authors_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search authors" %>
  <%= submit_tag "Search", :name => nil, class: "btn btn-primary" %>
<% end %>

<% if !params[:search] %>
  <%= link_to "Add author", new_author_path, class: "btn btn-primary" %>
<% end %>

<%#= will_paginate %>

<ul class="authors custom-list">
  <%= render @authors %>
</ul>

<%#= will_paginate %>

app/views/authors/new.html.erb
<% provide(:title, 'Create new author') %>
<h1>Create new author</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@author) do |f| %>
      <%= render 'shared/error_messages', object: @author %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.submit "Create author", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/authors/show.html.erb
<% provide_title(:title, @author.name) %>
<h1><%= @author.name %></h1>

<section class="books-list">
  <ul>
    <% @author.books.map do |book| %>
      <li><%= book.name %></li>
    <% end %>
  </ul>
</section>