config/routes.rb
SampleApp::Application.routes.draw do
  root 'static_pages#home'
  match "/help",     to: 'static_pages#help',     via: 'get'
  match "/about",    to: 'static_pages#about',    via: 'get'
  match "/contacts", to: 'static_pages#contacts', via: 'get'
  match "/signup",   to: 'users#new',             via: 'get'
  match '/signin',   to: 'sessions#new',          via: 'get'
  match '/signout',  to: 'sessions#destroy',      via: 'delete'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :books

  resources :authors

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :relationships
  has_many :authors, through: :relationships
  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :current_book, only: [:show, :add_author]
  before_action :filter_non_signed, only: [:index, :new, :show]

  def index
    if params[:search]
      @books = Book.find_by(name: params[:search])
    else
      @books = Book.paginate(page: params[:page])
    end
  end

  def show 
  end

  def add_author(author)
    @book.relationships.create(author: author)
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(params.require(:book).permit(:name))

    if @book.save
      flash.now[:success] = "Book successfully created!"
    else
      flash.now[:error] = "Book creation failed!"
    end

    render 'new'
  end

  private

    def current_book
      @book = Book.find(params[:id])
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<li>
  <%= link_to book.name, book %>
  <ul class="custom-sub-list">
    <% book.authors.map do |author| %>
      <li>
        <%= author.name %>
      </li>
    <% end %>
  </ul>
  <% if current_user.admin? %>
    | <%= link_to "delete", book, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/books/index.html.erb
<% provide(:title, 'All books') %>
<h1>All books</h1>

<%= form_tag(books_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search books" %>
  <%= submit_tag "Search", :name => nil, class: "btn btn-primary" %>
<% end %>

<% if !params[:search] %>
  <%= link_to "Add book", new_book_path, class: "btn btn-primary" %>
<% end %>

<%#= will_paginate %>

<ul class="books custom-list">
  <%= render @books %>
</ul>

<%#= will_paginate %>

app/views/books/new.html.erb
<% provide(:title, 'Create new book') %>
<h1>Create new book</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@book) do |f| %>
      <%= render 'shared/error_messages', object: @book %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.submit "Create book", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/books/show.html.erb
<% provide_title(:title, @book.name) %>
<h1><%= @book.name %></h1>

<section class="books-list">
  <ul>
    <% @book.authors.map do |author| %>
      <li><%= author.name %></li>
    <% end %>
  </ul>
</section>